#Caoimhe DeBuitlear student no: 19378783
#ca216/myshell

targets = myshell.c makerm_dir.c io_redirection.c help.c change_dir.c  input_from_file.c
all: build

build: 
		gcc -o ../bin/myshell $(targets)

clean: rm myshell
